### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by TwiShimmer** [HamsterYDS/UntilTheEndServer#1]
- 修复+1等聊天功能
- 命令自动补全，@后自动补全玩家
- 玩家输入fts help后全部前缀ignore不美观
- 椅子坐上后拆掉板砖/楼梯，玩家依然保持坐的bug
- 坐上椅子，射一支箭到椅子上，挖掉椅子，人退出重进，玩家按shift下来——制作浮空箭
- 电梯无视高度跨楼层到达
- Remove Herobrine
- 待补充

**Comment by TwiShimmer** [comment]
1.

**Comment by TwiShimmer** [comment]
补充：电梯方块下若无同类型电梯方块，按shift会卡死

**Comment by TwiShimmer** [comment]
补充：遗物箱会把已存在的方块卡掉，例如我服出现了卡掉信标的重大失误

**Comment by TwiShimmer** [comment]
补充：被苦力怕炸死的玩家，遗物箱子也会被炸烂

**Comment by IceBear003** [comment]
以上bugs在FTS-1.0.2已经修复
